site_name: DOME Recommendations Training Course
nav:
    - About: index.md
    - Course Content:
      - "Introduction": chapters/introduction.md
      - "1. Data": chapters/chapter_01.md
      - "2. Optimisation": chapters/chapter_02.md
      - "3. Model": chapters/chapter_03.md
      - "4. Evaluation": chapters/chapter_04.md
      - "Bring your Data": chapters/bring-your-data.md
      - "References": chapters/references.md
    - "Follow up training": follow_up_training.md

theme:
  name: material
  logo: assets/images/white-orange-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - toc.integrate
  font: 
    text: Lato

# Repository
repo_name: BiodataAnalysisGroup/DOME-Training-Course
repo_url: https://github.com/BiodataAnalysisGroup/DOME-Training-Course
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  - mkdocs-video # embed videos to the docs

  
# Footer
copyright: By the ELIXIR Training Platform

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - neoteroi.cards
  #- addbioschemas

extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
